// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.


import * as WebBrowser from "expo-web-browser";
import {Linking} from "expo";

const urlOpener = async (url, redirectUrl) => {
    // On Expo, use WebBrowser.openAuthSessionAsync to open the Hosted UI pages.
    const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(url, redirectUrl);

    if (type === 'success') {
        await WebBrowser.dismissBrowser();

        if (Platform.OS === 'ios') {
            return Linking.openURL(newUrl);
        }
    }
};

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:c6992300-1a10-4dae-b0ed-ec9b83a7e57b",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_DEPaV6AKY",
    "aws_user_pools_web_client_id": "444pnqt1nvclutln1i7jglhj4e",
    "oauth": {
        "domain": "amplify-auth-xedau-authxedau.auth.ap-northeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/",
        "redirectSignOut": "exp://127.0.0.1:19000/",
        "responseType": "code",
        // "urlOpener": urlOpener
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
